### PR TITLE
Update to Rust v1.77.2 and libcouchbase v3.3.12

### PR DESCRIPTION
**Pull request by ayushmishra2005**

### CODE REVIEW

**Comment by ayushmishra2005** [comment]
> Hi @ayushmishra2005 thanks, this looks good to me. Before we merge I think that we should fix CI though so that we can verify the change works on all platforms. I made a start at #153 but it needs some investigation what's going on with the Windows build.

Hi @chvck Thanks for raising #153 . I don't have a window machine but I will try to take a look and let you know if I find anything.

**Comment by chvck** [comment]
Looks like the problem might just be some Windows specific code.

**Comment by ayushmishra2005** [comment]
> Looks like the problem might just be some Windows specific code.

Yes @chvck you are right. I just pushed some changes to fix this. Could you please approve workflow?

**Comment by chvck** [comment]
This is looking good @ayushmishra2005 could you just update the commits to combine the similar commits; 1 for updating the readme, 1 for fixing tests, and 1 for refactoring please?

**Pull request merged**
